//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NP_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NP_Consumption
    {
        public System.Guid Guid { get; set; }
        public string card_no { get; set; }
        public System.DateTime consumption_date { get; set; }
        public System.Guid counter { get; set; }
        public int fee { get; set; }
        public int devidend { get; set; }
    }
}
